[2024-05-21T14:22:33.619+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T14:22:33.636+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.second_task manual__2024-05-21T14:22:30.635604+00:00 [queued]>
[2024-05-21T14:22:33.643+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.second_task manual__2024-05-21T14:22:30.635604+00:00 [queued]>
[2024-05-21T14:22:33.644+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-21T14:22:33.657+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): second_task> on 2024-05-21 14:22:30.635604+00:00
[2024-05-21T14:22:33.662+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2435) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T14:22:33.663+0000] {standard_task_runner.py:63} INFO - Started process 2437 to run task
[2024-05-21T14:22:33.663+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'manual__2024-05-21T14:22:30.635604+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpt9p3_cjc']
[2024-05-21T14:22:33.664+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask second_task
[2024-05-21T14:22:33.699+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag_v5.second_task manual__2024-05-21T14:22:30.635604+00:00 [running]> on host c420abfdc210
[2024-05-21T14:22:33.768+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Meier' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T14:22:30.635604+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T14:22:30.635604+00:00'
[2024-05-21T14:22:33.769+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T14:22:33.779+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-21T14:22:33.780+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2024-05-21T14:22:33.789+0000] {subprocess.py:86} INFO - Output:
[2024-05-21T14:22:33.790+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task1!
[2024-05-21T14:22:33.791+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-21T14:22:33.791+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T14:22:33.813+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, run_id=manual__2024-05-21T14:22:30.635604+00:00, execution_date=20240521T142230, start_date=20240521T142233, end_date=20240521T142233
[2024-05-21T14:22:33.837+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-21T14:22:33.849+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T14:22:33.852+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
